### ISSUE TITLE
Creator can add tasks.

### ISSUE THREAD

**Issue by jackdweber** [EECS448-KitchenUtensils/Skeddit#1]
The creator of an event should be able able to add a task list to an event (e.g. bring soda, bring salad, OR prepare slides, contact so-and-so)

**Comment by zjcers** [comment]
This is done and ready for review as of commit #0e53fc18e9e720e2d955e50ba34b92b2a6a8b24f.

**Comment by jackdweber** [comment]
Thanks qt;)

On Oct 4, 2017, at 10:26 PM, Zane Cersovsky <notifications@github.com<mailto:notifications@github.com>> wrote:


This is done and ready for review as of commit #0e53fc18e9e720e2d955e50ba34b92b2a6a8b24f.
