### ISSUE TITLE
Can't create an event with discontiguous timeslots

### ISSUE THREAD

**Issue by zjcers** [EECS448-KitchenUtensils/Skeddit#26]
When loading the event#new form, I am presented with a selector for start time and a selector for end time, but what if I want my event to go from 2-4PM, have a little break, and then resume for 7-9PM? According to the requirements (from Project 1), I should be able to do this.

**Comment by twalenczyk** [comment]
I'll start working on this.

**Comment by twalenczyk** [comment]
Closing. Jack created solved it using Add more. If you want a break in the event, just create the event with a contiguous body, i.e. 12pm - 4pm, then add more time slots, i.e. 5pm - 6pm.
