### ISSUE TITLE
Copy timeslots from day to day

### ISSUE THREAD

**Issue by zjcers** [EECS448-KitchenUtensils/Skeddit#4]
Allow the option to pick all times from one day (e.g. 4 time slots on Monday) and copy those time slots to another day (e.g. use the same time slots from Monday on Wednesday). This is to help avoid reenter times over and over

**Comment by jackdweber** [comment]
Once done with models and new forms created, Ill make the javascript to show more days and it'll be pre-filled.

**Comment by jackdweber** [comment]
New creation form should autofill
